import type { AnimationDef, AnimProperties, AnimationName } from './types';

export const ANIM_PROPERTIES: Record<AnimationName, AnimProperties> = {
  idle: { loop: true },
  advance: { loop: true },
  retreat: { loop: true },
  attack: { loop: false, returnTo: 'idle' },
  defend: { loop: false, returnTo: 'idle' },
  special: { loop: false, returnTo: 'idle' },
};

export const ANIMATIONS: Record<AnimationName, AnimationDef> = {
  idle: {
    name: 'Idle',
    totalFrames: 120,
    fps: 60,
    description: 'Gentle bob with smooth easing',
    keyframes: {
      0: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 30, dx: 0, dy: -1, ease: 'easeInOutQuad' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeInOutQuad' },
        { frame: 90, dx: 0, dy: 1, ease: 'easeInOutQuad' },
      ],
      1: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 30, dx: -1, dy: 0, ease: 'easeInOutQuad' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeInOutQuad' },
        { frame: 90, dx: 1, dy: 0, ease: 'easeInOutQuad' },
      ],
      2: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 30, dx: 1, dy: 0, ease: 'easeInOutQuad' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeInOutQuad' },
        { frame: 90, dx: -1, dy: 0, ease: 'easeInOutQuad' },
      ],
      3: [
        { frame: 0, dx: 1, dy: 0 },
        { frame: 30, dx: 0, dy: -1, ease: 'easeInOutQuad' },
        { frame: 60, dx: -1, dy: 0, ease: 'easeInOutQuad' },
        { frame: 90, dx: 0, dy: 1, ease: 'easeInOutQuad' },
      ],
      4: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 30, dx: 0, dy: -1, ease: 'easeInOutQuad' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeInOutQuad' },
        { frame: 90, dx: 0, dy: 1, ease: 'easeInOutQuad' },
      ],
      5: [],
    },
  },
  advance: {
    name: 'Advance',
    totalFrames: 60,
    fps: 60,
    description: 'Scuttle forward with natural gait easing',
    keyframes: {
      0: [
        { frame: 0, dx: -1, dy: 0 },
        { frame: 15, dx: -1, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: -1, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: -1, dy: 1, ease: 'easeOutQuad' },
      ],
      1: [
        { frame: 0, dx: -2, dy: 0 },
        { frame: 15, dx: -2, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: -2, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: -2, dy: 1, ease: 'easeOutQuad' },
      ],
      2: [
        { frame: 0, dx: 1, dy: 0 },
        { frame: 15, dx: 1, dy: -1, ease: 'easeOutQuad' },
        { frame: 30, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: 1, dy: -1, ease: 'easeOutQuad' },
      ],
      3: [
        { frame: 0, dx: -2, dy: 0 },
        { frame: 15, dx: -1, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: -2, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: -1, dy: 1, ease: 'easeOutQuad' },
      ],
      4: [
        { frame: 0, dx: -1, dy: 0 },
        { frame: 15, dx: -1, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: -1, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: -1, dy: 1, ease: 'easeOutQuad' },
      ],
      5: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: -1, dy: -1, ease: 'easeOutQuad' },
        { frame: 20, dx: -1, dy: 0, ease: 'easeInQuad' },
        { frame: 30, dx: 0, dy: 0 },
        { frame: 40, dx: -1, dy: -1, ease: 'easeOutQuad' },
        { frame: 50, dx: -1, dy: 0, ease: 'easeInQuad' },
      ],
    },
  },
  retreat: {
    name: 'Retreat',
    totalFrames: 60,
    fps: 60,
    description: 'Scuttle backward with lean-back easing',
    keyframes: {
      0: [
        { frame: 0, dx: 1, dy: 0 },
        { frame: 15, dx: 1, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: 1, dy: 1, ease: 'easeOutQuad' },
      ],
      1: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 15, dx: 0, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: 0, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: 0, dy: 1, ease: 'easeOutQuad' },
      ],
      2: [
        { frame: 0, dx: 2, dy: 0 },
        { frame: 15, dx: 2, dy: -1, ease: 'easeOutQuad' },
        { frame: 30, dx: 2, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: 2, dy: -1, ease: 'easeOutQuad' },
      ],
      3: [
        { frame: 0, dx: 1, dy: 0 },
        { frame: 15, dx: 2, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: 2, dy: 1, ease: 'easeOutQuad' },
      ],
      4: [
        { frame: 0, dx: 1, dy: 0 },
        { frame: 15, dx: 1, dy: 1, ease: 'easeOutQuad' },
        { frame: 30, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: 1, dy: 1, ease: 'easeOutQuad' },
      ],
      5: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: 1, dy: -1, ease: 'easeOutQuad' },
        { frame: 20, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 30, dx: 0, dy: 0 },
        { frame: 40, dx: 1, dy: -1, ease: 'easeOutQuad' },
        { frame: 50, dx: 1, dy: 0, ease: 'easeInQuad' },
      ],
    },
  },
  attack: {
    name: 'Attack',
    totalFrames: 75,
    fps: 60,
    description: 'Wind-back then explosive lunge with easeOutBack strike',
    keyframes: {
      0: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 18, dx: 2, dy: 0, ease: 'easeInCubic' },
        { frame: 30, dx: -3, dy: -1, ease: 'easeOutBack' },
        { frame: 42, dx: -2, dy: 0, ease: 'easeOutCubic' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeOutCubic' },
      ],
      1: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 18, dx: 3, dy: 1, ease: 'easeInCubic' },
        { frame: 28, dx: -5, dy: -1, ease: 'easeOutBack' },
        { frame: 42, dx: -3, dy: 0, ease: 'easeOutCubic' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeOutCubic' },
      ],
      2: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 18, dx: 0, dy: -1, ease: 'easeInQuad' },
        { frame: 30, dx: 2, dy: 1, ease: 'easeOutBack' },
        { frame: 45, dx: 1, dy: 0, ease: 'easeOutCubic' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeOutCubic' },
      ],
      3: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 18, dx: 3, dy: 0, ease: 'easeInCubic' },
        { frame: 30, dx: -4, dy: -1, ease: 'easeOutBack' },
        { frame: 42, dx: -2, dy: 0, ease: 'easeOutCubic' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeOutCubic' },
      ],
      4: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 18, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 30, dx: -3, dy: -1, ease: 'easeOutBack' },
        { frame: 45, dx: -1, dy: 0, ease: 'easeOutCubic' },
        { frame: 60, dx: 0, dy: 0, ease: 'easeOutCubic' },
      ],
      5: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 18, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 30, dx: -1, dy: 0, ease: 'easeOutQuad' },
      ],
    },
  },
  defend: {
    name: 'Defend',
    totalFrames: 60,
    fps: 60,
    description: 'Quick hunch with easeOutCubic snap',
    keyframes: {
      0: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: 0, dy: 2, ease: 'easeOutCubic' },
        { frame: 40, dx: 0, dy: 2 },
        { frame: 55, dx: 0, dy: 0, ease: 'easeInOutQuad' },
      ],
      1: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: 3, dy: 1, ease: 'easeOutCubic' },
        { frame: 40, dx: 3, dy: 1 },
        { frame: 55, dx: 0, dy: 0, ease: 'easeInOutQuad' },
      ],
      2: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: 0, dy: 1, ease: 'easeOutCubic' },
        { frame: 40, dx: 0, dy: 1 },
        { frame: 55, dx: 0, dy: 0, ease: 'easeInOutQuad' },
      ],
      3: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: 1, dy: 2, ease: 'easeOutCubic' },
        { frame: 40, dx: 1, dy: 2 },
        { frame: 55, dx: 0, dy: 0, ease: 'easeInOutQuad' },
      ],
      4: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: 0, dy: 2, ease: 'easeOutCubic' },
        { frame: 40, dx: 0, dy: 2 },
        { frame: 55, dx: 0, dy: 0, ease: 'easeInOutQuad' },
      ],
      5: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 10, dx: 0, dy: 1, ease: 'easeOutCubic' },
        { frame: 40, dx: 0, dy: 1 },
        { frame: 55, dx: 0, dy: 0, ease: 'easeInOutQuad' },
      ],
    },
  },
  special: {
    name: 'Special',
    totalFrames: 105,
    fps: 60,
    description: 'Charge with easeInQuad, explosive easeOutElastic release, bounce settle',
    keyframes: {
      0: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 25, dx: 3, dy: -1, ease: 'easeInQuad' },
        { frame: 45, dx: 3, dy: -2, ease: 'easeInOutQuad' },
        { frame: 55, dx: -5, dy: 1, ease: 'easeOutElastic' },
        { frame: 70, dx: -3, dy: 0, ease: 'easeOutCubic' },
        { frame: 90, dx: 0, dy: 0, ease: 'bounce' },
      ],
      1: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 25, dx: 4, dy: 1, ease: 'easeInQuad' },
        { frame: 45, dx: 4, dy: 2, ease: 'easeInOutQuad' },
        { frame: 55, dx: -6, dy: -2, ease: 'easeOutElastic' },
        { frame: 68, dx: -4, dy: -1, ease: 'easeOutCubic' },
        { frame: 90, dx: 0, dy: 0, ease: 'bounce' },
      ],
      2: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 25, dx: 2, dy: -1, ease: 'easeInQuad' },
        { frame: 45, dx: 3, dy: -1, ease: 'easeInOutQuad' },
        { frame: 55, dx: -1, dy: 1, ease: 'easeOutBack' },
        { frame: 70, dx: 1, dy: 0, ease: 'easeOutCubic' },
        { frame: 90, dx: 0, dy: 0, ease: 'bounce' },
      ],
      3: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 25, dx: 4, dy: -1, ease: 'easeInQuad' },
        { frame: 35, dx: 2, dy: -2 },
        { frame: 45, dx: 4, dy: -2, ease: 'easeInOutQuad' },
        { frame: 55, dx: -7, dy: 1, ease: 'easeOutElastic' },
        { frame: 70, dx: -4, dy: 0, ease: 'easeOutCubic' },
        { frame: 90, dx: 0, dy: 0, ease: 'bounce' },
      ],
      4: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 25, dx: 2, dy: -1, ease: 'easeInQuad' },
        { frame: 45, dx: 2, dy: -2, ease: 'easeInOutQuad' },
        { frame: 55, dx: -5, dy: 1, ease: 'easeOutElastic' },
        { frame: 70, dx: -3, dy: 0, ease: 'easeOutCubic' },
        { frame: 90, dx: 0, dy: 0, ease: 'bounce' },
      ],
      5: [
        { frame: 0, dx: 0, dy: 0 },
        { frame: 25, dx: 1, dy: 0, ease: 'easeInQuad' },
        { frame: 45, dx: 1, dy: 1, ease: 'easeInOutQuad' },
        { frame: 55, dx: -1, dy: 0, ease: 'easeOutBack' },
        { frame: 70, dx: 0, dy: 0, ease: 'easeOutCubic' },
      ],
    },
  },
};
