using UnityEngine;

/// <summary>
/// Where the painted content actually sits inside each arena layer's canvas.
///
/// Every arena layer the designer ships is a full-frame 640x360 sprite — a rock ledge along
/// the bottom, a clam at the left edge, a chest bleeding off the right — so a sprite's bounds
/// say nothing about what is drawn in it. Scaling such a layer about the camera centre (the
/// first attempt at de-crowding the boards) pulled every painted edge inward and left the art
/// floating off the frame. With the content's bounding box we can shrink each layer about the
/// edge it is welded to instead, so it gets smaller without ever detaching.
///
/// Generated by Clawbada ▸ Arena ▸ Bake Decor Anchors; read at runtime by BattleManager.
/// Re-run it after an arena art drop — a sprite with no entry is simply left at full size.
/// </summary>
public class ArenaDecorAnchors : ScriptableObject
{
    public const string ResourcePath = "ArenaDecorAnchors";

    [System.Serializable]
    public class Entry
    {
        [Tooltip("Tier folder + sprite name, e.g. \"Elite/FG - 1 - Rock\" — layer names repeat across tiers.")]
        public string sprite;
        [Tooltip("Opaque content bounds as a fraction of the canvas: x/y = left/bottom, z/w = right/top.")]
        public Vector4 content;
    }

    public Entry[] entries = new Entry[0];

    /// <summary>Content box for a tier's layer, or null when it was never baked.
    /// Keyed by tier because "BG - 2" and "FG - 1" exist in more than one arena.</summary>
    public Vector4? For(string tier, string sprite)
    {
        if (entries == null || string.IsNullOrEmpty(sprite)) return null;
        string key = $"{tier}/{sprite}";
        foreach (var e in entries)
            if (e != null && string.Equals(e.sprite, key, System.StringComparison.OrdinalIgnoreCase)) return e.content;
        return null;
    }
}
