/**
 * Encode arena music masters into the web app as content-hashed AAC and generate the
 * lookup React imports at build time.
 *
 *   bun scripts/build-music.ts                 # masters from audio-masters/music/
 *   bun scripts/build-music.ts --in <dir>      # elsewhere
 *   bun scripts/build-music.ts --bitrate 160k  # default 128k
 *
 * Why this shape:
 *  - Music is NOT in the Unity bundle: it is served as its own file and streamed by an
 *    HTML5 <audio> element from React, like the landing-page theme. The bundle stays small,
 *    only the arena you enter is downloaded, and it starts within a second.
 *  - The filename carries a content hash, so /audio/music/* can be cached as immutable for a
 *    year and still invalidate the moment a track changes. The mapping is baked into a
 *    generated TS module (itself hashed by Next), so there is no runtime manifest fetch.
 *  - AAC (m4a), not OGG: URL-loaded audio is decoded by the browser, and Safari cannot decode
 *    Vorbis. Apple's encoder (aac_at) is used when ffmpeg has it, else ffmpeg's own.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';

const args = process.argv.slice(2);
const opt = (k: string, d: string) => { const i = args.indexOf(`--${k}`); return i >= 0 ? args[i + 1] : d; };
const root = resolve(import.meta.dir, '..');
const inDir = resolve(opt('in', join(root, 'audio-masters/music')));
const bitrate = opt('bitrate', '128k');
const outDir = join(root, 'apps/web/public/audio/music');
const genPath = join(root, 'apps/web/src/lib/arena-music.generated.ts');
const TIERS = ['evolved', 'elite', 'apex'] as const;

mkdirSync(outDir, { recursive: true });
const masters = existsSync(inDir) ? readdirSync(inDir).filter((f) => /^BGM_Arena_(Evolved|Elite|Apex)\.wav$/i.test(f)) : [];
if (masters.length === 0) { console.error(`no BGM_Arena_<Tier>.wav masters in ${inDir}`); process.exit(1); }

const urls: Record<string, string | null> = { evolved: null, elite: null, apex: null };
const keep = new Set<string>();
for (const file of masters) {
  const tier = basename(file, '.wav').split('_')[2].toLowerCase();
  const tmp = join(outDir, `.${basename(file, '.wav')}.tmp.m4a`);
  const enc = (codec: string) => Bun.spawnSync(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-i', join(inDir, file),
    '-vn', '-c:a', codec, '-b:a', bitrate, '-movflags', '+faststart', tmp]);
  let r = enc('aac_at');
  if (r.exitCode !== 0) r = enc('aac');
  if (r.exitCode !== 0) { console.error(`ffmpeg failed for ${file}:\n${new TextDecoder().decode(r.stderr)}`); process.exit(1); }
  const bytes = readFileSync(tmp);
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8);
  const name = `${basename(file, '.wav')}.${hash}.m4a`;
  rmSync(join(outDir, name), { force: true });
  Bun.spawnSync(['mv', tmp, join(outDir, name)]);
  keep.add(name);
  urls[tier] = `/audio/music/${name}`;
  console.log(`${file} → ${name}  ${(bytes.length / 1048576).toFixed(2)} MB @ ${bitrate}`);
}
// Drop stale hashed variants of the same tracks so the folder only holds what the app references.
for (const f of readdirSync(outDir)) if (/^BGM_Arena_(Evolved|Elite|Apex)\.[0-9a-f]{8}\.m4a$/.test(f) && !keep.has(f)) { rmSync(join(outDir, f)); console.log(`removed stale ${f}`); }

const body = TIERS.map((t) => `  ${t}: ${urls[t] ? JSON.stringify(urls[t]) : 'null'},`).join('\n');
writeFileSync(genPath, `// GENERATED by scripts/build-music.ts — do not edit. Re-run after changing a master.
export type ArenaTier = 'evolved' | 'elite' | 'apex';
/** Content-hashed URLs, served immutable from public/audio/music/. null = no track for that tier. */
export const ARENA_MUSIC: Record<ArenaTier, string | null> = {
${body}
};
`);
console.log(`wrote ${genPath.replace(root + '/', '')}`);
