// GENERATED by scripts/build-music.ts — do not edit. Re-run after changing a master.
export type ArenaTier = 'evolved' | 'elite' | 'apex';
/** Content-hashed URLs, served immutable from public/audio/music/. null = no track for that tier. */
export const ARENA_MUSIC: Record<ArenaTier, string | null> = {
  evolved: "/audio/music/BGM_Arena_Evolved.88373004.m4a",
  elite: "/audio/music/BGM_Arena_Elite.a5ec31e8.m4a",
  apex: "/audio/music/BGM_Arena_Apex.89e37876.m4a",
};
